name: Daily Tesla Update

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch:       # Allow manual runs for testing

jobs:
  daily_update:
    runs-on: ubuntu-latest

    env:
      ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_CX: ${{ secrets.GOOGLE_CX }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug info
        run: |
          echo "===== DEBUG INFO ====="
          echo "Current UTC time: $(date -u)"
          echo "Branch: $GITHUB_REF"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "======================"

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install "numpy<2"  # ensure a stable version compatible with pandas
          pip install -r requirements.txt


      - name: Fetch stock data
        run: python fetch_data.py

      - name: Plot chart
        run: python plot_chart.py

      - name: Fetch news
        run: python fetch_news.py

      - name: Update README
        run: python update_readme.py

      - name: List generated files
        run: |
          echo "===== Generated files ====="
          ls -lh charts/ || true
          ls -lh data/ || true
          ls -lh news/ || true
          echo "==========================="

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'Tesla Bot'
          author_email: 'actions@github.com'
          message: 'Daily update: Tesla stock chart and news'
          add: 'charts/*.png data/*.csv news/*.json README.md'
